# language.py

LANGUAGES = {
    "EN": {
        "window_title": "iyo's Variant Generator",
        "frame_scenario": "1. Select Scenario",
        "label_folder_path": "Folder Path:",
        "button_browse": "Browse...",
        "label_scenario_name": "Scenario Name:",
        "frame_profiles": "Settings Profile",
        "label_active_profile": "Active Profile:",
        "button_new": "New Profile",  # --- CHANGED ---
        "button_rename": "Rename",
        "button_delete": "Delete",
        "frame_stats": "2. Detected Base Stats",
        "stats_scenario_name": "Scenario Name: N/A",
        "stats_targets": "Target(s):",
        "stats_hp": "Target HP:",
        "stats_regen": "Target Regen/s:",
        "stats_radius": "Target Radius:",
        "stats_head_radius": "Target Head Radius:",
        "stats_speed": "Target Max Speed:",
        "stats_timescale": "Timescale:",
        "stats_duration": "Duration:",
        "frame_variants": "3. Choose Variants to Create",
        "button_edit_values": "Edit Values",
        "button_save_values": "Save Values",
        "button_generate": "Generate Variants",
        "frame_log": "Status Log",
        "button_select_all": "Select All",
        "button_deselect_all": "Deselect All",
        "dialog_overwrite_title": "Overwrite Confirmation",
        "dialog_overwrite_text": 'The file "{filename}" already exists.\n\nHow would you like to proceed for this and all future conflicts in this batch?',
        "dialog_save_profile_title": "Save Profile As", # Not used anymore but okay to keep
        "dialog_save_profile_prompt": "Enter a name for the new profile:", # Not used anymore
        "dialog_rename_profile_title": "Rename Profile",
        "dialog_rename_profile_prompt": "Enter a new name for '{old_name}':",
        "dialog_confirm_delete_title": "Confirm Delete",
        "dialog_confirm_delete_prompt": "Are you sure you want to delete the profile '{profile_to_delete}'?",
        "error_profile_exists": "A profile with this name already exists.",
        "error_delete_last_profile": "Cannot delete the last profile.",
        "error_tags_empty": "Variant tags cannot be empty.",
        "error_must_be_whole_numbers": "All numeric values must be whole numbers.",
        "frame_targets_modify": "Targets to Modify (de-select player and/or helper characters)",
    },
    "JP": {
        "window_title": "派生シナリオメーカー by iyo",
        "frame_scenario": "1. シナリオを選択",
        "label_folder_path": "フォルダパス:",
        "button_browse": "参照...",
        "label_scenario_name": "シナリオ名:",
        "frame_profiles": "設定プロファイル",
        "label_active_profile": "現在のプロファイル:",
        "button_new": "新規作成", 
        "button_rename": "名前の変更",
        "button_delete": "削除",
        "frame_stats": "2. 検出された基本ステータス",
        "stats_scenario_name": "シナリオ名: N/A",
        "stats_targets": "ターゲット:",
        "stats_hp": "ターゲットHP:",
        "stats_regen": "ターゲット回復/秒:",
        "stats_radius": "ターゲットの半径:",
        "stats_head_radius": "ターゲットの頭部半径:",
        "stats_speed": "ターゲットの最大速度:",
        "stats_timescale": "タイムスケール:",
        "stats_duration": "持続時間:",
        "frame_variants": "3. 作成する派生シナリオを選択",
        "button_edit_values": "値を編集",
        "button_save_values": "値を保存",
        "button_generate": "派生シナリオを生成",
        "frame_log": "ステータスログ",
        "button_select_all": "すべて選択",
        "button_deselect_all": "すべて選択解除",
        "dialog_overwrite_title": "上書き確認",
        "dialog_overwrite_text": 'ファイル "{filename}" は既に存在します。\n\nこのファイルおよび今後の競合に対してどのように処理しますか？',
        "dialog_save_profile_title": "プロファイルを名前を付けて保存",
        "dialog_save_profile_prompt": "新しいプロファイルの名前を入力してください:",
        "dialog_rename_profile_title": "プロファイルの名前を変更",
        "dialog_rename_profile_prompt": "'{old_name}' の新しい名前を入力してください:",
        "dialog_confirm_delete_title": "削除の確認",
        "dialog_confirm_delete_prompt": "本当にプロファイル '{profile_to_delete}' を削除しますか？",
        "error_profile_exists": "この名前のプロファイルは既に存在します。",
        "error_delete_last_profile": "最後のプロファイルを削除することはできません。",
        "error_tags_empty": "バリアントタグを空にすることはできません。",
        "error_must_be_whole_numbers": "すべての数値は整数でなければなりません。",
        "frame_targets_modify": "変更するターゲット (プレイヤー、ヘルバーキャラクターの選択を解除してください)",
    }
}